/******************************************************************************
 * Begin of file fontlibrary.h
 * @author: Niek Klaverstijn
 * @version: 1.0
 * Created: 14-05-2016
 *
 *~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~**/
/** @file
 * @brief Header file for bitmaps
 * Generated by edited bcmfont2c.py
 * Source: http://larsee.dk/converting-fonts-to-c-source-using-bmfont2c/
 ******************************************************************************/
#ifndef FONTLIBRARY_H_
#define FONTLIBRARY_H_

/** @brief Roboto size 18 font. */
extern fontStyle_t FontStyle_Roboto18;

/** @brief Roboto size 18 bold font. */
extern fontStyle_t FontStyle_Roboto18Bold;

/** @brief Roboto size 12 font. */
extern fontStyle_t FontStyle_Roboto12;

/** @brief Roboto size 12 bold font. */
extern fontStyle_t FontStyle_Roboto12Bold;

/** @brief Emoji size 24 font. */
extern fontStyle_t FontStyle_NotoEmoji24;

/** @brief Roboto size 24 slab font. */
extern fontStyle_t FontStyle_RobotoSlab24;

/** @brief Roboto size 24 slab bold font. */
extern fontStyle_t FontStyle_RobotoSlab24Bold;

#endif /* FONTLIBRARY_H_ */
/* End of file fontlibrary.h */
