/******************************************************************************
 * Begin of file fontlibrary.h
 * @author: Niek Klaverstijn
 * @version: 1.0
 * Created: 14-05-2016
 *
 *~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~**/
/** @file
 * @brief Header file for bitmaps
 * Generated by edited bcmfont2c.py
 * Source: http://larsee.dk/converting-fonts-to-c-source-using-bmfont2c/
 ******************************************************************************/
#ifndef FONTLIBRARY_H_
#define FONTLIBRARY_H_

typedef struct
{
    uint8_t GlyphCount;
    uint8_t FirstAsciiCode;
    uint8_t GlyphBytesWidth;
    uint8_t GlyphHeight;
    uint8_t FixedWidth;
    uint8_t const *GlyphWidth;
    uint8_t const *GlyphBitmaps;
} fontStyle_t;

extern fontStyle_t FontStyle_Roboto18;
extern fontStyle_t FontStyle_Roboto18Bold;
extern fontStyle_t FontStyle_Roboto12;
extern fontStyle_t FontStyle_Roboto12Bold;

#endif /* FONTLIBRARY_H_ */
/* End of file fontlibrary.h */
